[package]
name = "ni-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
float-ord = "0.3.2"
itertools = "0.11.0"
ni-usb-6259 = {path = "../ni-usb-6259"}
